version: '3'

services:
  php:
    build:
      context: ./docker
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    depends_on:
      - redis

  nginx:
    image: nginx:1-alpine
    restart: unless-stopped
    depends_on:
      - php
    ports:
      - "89:80"
      - "8443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'

    
