name: CI

on:
    push:
      branches:  [ main ]
    pull_request:
      branches:  [ main ]

jobs:
  phpunit:
    name: PHPUnit
    runs-on: 'ubuntu-latest'
    
    services:
      
      redis:
        image: redis:7-alpine
        restart: unless-stopped
        ports:
          - '${REDIS_PORT:-6379}:6379'
        environment:
          - REDIS_PORT=${REDIS_PORT}
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
        
      - name: PHPUnit
        uses: chindit/actions-phpunit-symfony@master
          
      
            
